### ISSUE TITLE
Create sessions API

### ISSUE THREAD

**Issue by prasadpilla** [coronagoapp/coronago-backend#3]
This API is to start/end social distancing sessions.

The sessions are of two types: home and non-home. We reward people for "home" sessions and penalise for "non-home" sessions.

Reward: 1 point for every 10 mins
Penalty: 10 points for every 10 mins

1. Create a migration and model for Session with fields start_time, end_time, type(enum: home, non-home), rewards
2. /sessions/start -->Should create a new session and mark the session "in-progress"
                                --> Should update current active session's end_time and calculate rewards(both positive and negative), update user wallet, make an entry into wallet_transactions table.
4. Document the API in postman, get the link from README

**Comment by gr1d99** [comment]
@prasadpilla I would like to work on this

**Comment by prasadpilla** [comment]
@gr1d99 Any update on this? App dev team will need this for integration today

**Comment by gr1d99** [comment]
@prasadpilla I have raised a WIP.

Question:
1. Will the `start_time` be sent by the frontend through a POST request? I think it would be better handled by the backend so that the value that is received from the frontend is `session type, either 'home' or 'away'`

**Comment by gr1d99** [comment]
2. Can a user have more than one active session? I was thinking if a user has an active session and for some reason, another request is made to start another session again. I was thinking we end the existing session before a new one is started.

What are your thoughts on this?

**Comment by prasadpilla** [comment]
> @prasadpilla I have raised a WIP.
> 
> Question:
> 
> 1. Will the `start_time` be sent by the frontend through a POST request? I think it would be better handled by the backend so that the value that is received from the frontend is `session type, either 'home' or 'away'`

@gr1d99 yeah this sounds good. They can just send the type.and we can update the start_time in the backend.

**Comment by prasadpilla** [comment]
> 1. Can a user have more than one active session? I was thinking if a user has an active session and for some reason, another request is made to start another session again. Then we end the existing session before a new one is started.
> 
> What are your thoughts on this?

@gr1d99 There should be only one session "in-progress" at a time. That's why i didn't add any params in the /end endpoint, so we just pick up the last active session and end it. 

And yes, to make the /start endpoint idempotent we should end the active session.

**Comment by gr1d99** [comment]
great!, I am almost done.
