### ISSUE TITLE
Create Leaderboard API

### ISSUE THREAD

**Issue by prasadpilla** [coronagoapp/coronago-backend#4]
1. Create Endpoint to return leaderboard ordered by wallet_balance

**Comment by arunava59** [comment]
I would like to take up this task.
Also, what columns you want in the leaderboard ? I am thinking of Name, Wallet Balance and Country. Is anything more required ?

**Comment by prasadpilla** [comment]
> I would like to take up this task.
> Also, what columns you want in the leaderboard ? I am thinking of Name, Wallet Balance and Country. Is anything more required ?

@arunava59 yes those fields should be enough for V1. 

Just to be clear, we don't need another model, we just need to query data and send it in the response.

Since we already have the UserSerializer, you can make use of that.

Here is a  snippet to do that,    
 `renderjson: ActiveModel::Serializer::CollectionSerializer.new(@users, each_serializer: UserSerializer).as_json`

**Comment by arunava59** [comment]
Yes, I understood. On it.

**Comment by prasadpilla** [comment]
> I would like to take up this task.
> Also, what columns you want in the leaderboard ? I am thinking of Name, Wallet Balance and Country. Is anything more required ?

@arunava59 



> Yes, I understood. On it.

@arunava59 oh yeah i forgot, we need the rank as well.

**Comment by arunava59** [comment]
Okay, there are 2 more points for clarification.

1. Will the leaderboard be public and visible to all ? Or would it be visible only to the logged in users ?
2. I assume we would be paginating the sorted data, say top 10 or 15 or K amount of users visible on the first page. In such case what would be the value of K ?

**Comment by prasadpilla** [comment]
> Okay, there are 2 more points for clarification.
> 
> 1. Will the leaderboard be public and visible to all ? Or would it be visible only to the logged in users ?
> 2. I assume we would be paginating the sorted data, say top 10 or 15 or K amount of users visible on the first page. In such case what would be the value of K ?

@arunava59 As i think more about it, doesn't look like it's just not simple "Querying" as i mentioned earlier. 

It's a very complex functionality. Fortunately there are gems to do that, https://www.sitepoint.com/leaderboards-rails/
https://github.com/agoragames/leaderboard
Please have a look. 

And for your questions Q1: yes it's only for users Q2: Yes we just need to return top 10 people for now, no pagination required because it's only 10 and current_user's rank

**Comment by arunava59** [comment]
Please review PR: https://github.com/coronagoapp/coronago-backend/pull/14
