### ISSUE TITLE
Add validation to User model to block multiple home location updates

### ISSUE THREAD

**Issue by prasadpilla** [coronagoapp/coronago-backend#6]
Once the home location is set, user shouldn't be able to change it. 
Please add a validation for this.

**Comment by arunava59** [comment]
By home location we mean "lat" and "lon" fields, right ?

**Comment by prasadpilla** [comment]
> By home location we mean "lat" and "lon" fields, right ?
@arunava59 yes

**Comment by arunava59** [comment]
I would like to start this task. Can you assign it to me ?

**Comment by prasadpilla** [comment]
> I would like to start this task. Can you assign it to me ?

@arunava59 Done

**Comment by arunava59** [comment]
PR for this issue - https://github.com/arbob/Coronago-backend/pull/8
Please review.
